//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTag
    {
        public int RecipeTagId { get; set; }
        public int RecipeId { get; set; }
        public int TagId { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
